[package]
name = "rust-knowledge"
version = "0.1.0"
authors = ["Ferenc Szujo <loopilla@gmail.com>"]
edition = "2018"

[[example]]
name = "ownership"

[[example]]
name = "structs"

[[example]]
name = "enums"